import type {ESLint, Linter} from 'eslint';
import globals from 'globals';
import jest from 'eslint-plugin-jest';
import {importX} from 'eslint-plugin-import-x';
// @ts-expect-error - no types available
import eslintComments from '@eslint-community/eslint-plugin-eslint-comments';
// @ts-expect-error - no types available
import importNewlines from 'eslint-plugin-import-newlines';
// @ts-expect-error - no types available
import newlineDestructuring from 'eslint-plugin-newline-destructuring';
// @ts-expect-error - no types available
import stylistic from '@stylistic/eslint-plugin';

const baseRules: Linter.RulesRecord = {
    // Custom rules
    '@croct/argument-spacing': 'error',
    '@croct/complex-expression-spacing': 'error',
    '@croct/newline-per-chained-call': 'error',
    '@croct/min-chained-call-depth': 'error',
    '@croct/parameter-destructuring': 'error',

    // ESLint comments rules
    '@eslint-community/eslint-comments/disable-enable-pair': [
        'error',
        {
            allowWholeFile: true,
        },
    ],
    '@eslint-community/eslint-comments/require-description': 'error',
    '@eslint-community/eslint-comments/no-unused-disable': 'error',

    // Best practices (from airbnb-base)
    'accessor-pairs': 'off',
    'array-callback-return': ['error', {allowImplicit: true}],
    'block-scoped-var': 'error',
    complexity: ['off', 20],
    'class-methods-use-this': 'off',
    'consistent-return': 'off',
    curly: ['error', 'multi-line'],
    'default-case': 'off',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': ['error', {allowKeywords: true}],
    '@stylistic/dot-location': ['error', 'property'],
    eqeqeq: ['error', 'always', {null: 'ignore'}],
    'grouped-accessor-pairs': 'error',
    'guard-for-in': 'error',
    'max-classes-per-file': 'off',
    'no-alert': 'warn',
    'no-caller': 'error',
    'no-case-declarations': 'error',
    'no-constructor-return': 'error',
    'no-div-regex': 'off',
    'no-else-return': ['error', {allowElseIf: false}],
    'no-empty-function': ['error', {
        allow: [
            'arrowFunctions',
            'functions',
            'methods',
        ],
    }],
    'no-empty-pattern': 'error',
    'no-eq-null': 'off',
    'no-eval': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-label': 'error',
    'no-fallthrough': 'error',
    '@stylistic/no-floating-decimal': 'error',
    'no-global-assign': ['error', {exceptions: []}],
    'no-native-reassign': 'off',
    'no-implicit-coercion': ['off', {
        boolean: false,
        number: true,
        string: true,
        allow: [],
    }],
    'no-implicit-globals': 'off',
    'no-implied-eval': 'error',
    'no-invalid-this': 'off',
    'no-iterator': 'error',
    'no-labels': ['error', {allowLoop: false, allowSwitch: false}],
    'no-lone-blocks': 'error',
    'no-loop-func': 'error',
    'no-magic-numbers': ['off', {
        ignore: [],
        ignoreArrayIndexes: true,
        enforceConst: true,
        detectObjects: false,
    }],
    '@stylistic/no-multi-spaces': ['error', {
        ignoreEOLComments: false,
    }],
    'no-multi-str': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': ['error', {
        props: true,
        ignorePropertyModificationsFor: [
            'acc',
            'accumulator',
            'e',
            'ctx',
            'context',
            'req',
            'request',
            'res',
            'response',
            '$scope',
            'staticContext',
        ],
    }],
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-restricted-properties': ['error', {
        object: 'arguments',
        property: 'callee',
        message: 'arguments.callee is deprecated',
    }, {
        object: 'global',
        property: 'isFinite',
        message: 'Please use Number.isFinite instead',
    }, {
        object: 'self',
        property: 'isFinite',
        message: 'Please use Number.isFinite instead',
    }, {
        object: 'window',
        property: 'isFinite',
        message: 'Please use Number.isFinite instead',
    }, {
        object: 'global',
        property: 'isNaN',
        message: 'Please use Number.isNaN instead',
    }, {
        object: 'self',
        property: 'isNaN',
        message: 'Please use Number.isNaN instead',
    }, {
        object: 'window',
        property: 'isNaN',
        message: 'Please use Number.isNaN instead',
    }, {
        property: '__defineGetter__',
        message: 'Please use Object.defineProperty instead.',
    }, {
        property: '__defineSetter__',
        message: 'Please use Object.defineProperty instead.',
    }, {
        object: 'Math',
        property: 'pow',
        message: 'Use the exponentiation operator (**) instead.',
    }],
    'no-return-assign': ['error', 'always'],
    'no-return-await': 'error',
    'no-script-url': 'error',
    'no-self-assign': ['error', {
        props: true,
    }],
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unmodified-loop-condition': 'off',
    'no-unused-expressions': 'error',
    'no-unused-labels': 'error',
    'no-useless-call': 'off',
    'no-useless-catch': 'error',
    'no-useless-concat': 'error',
    'no-useless-escape': 'error',
    'no-useless-return': 'error',
    'no-void': 'error',
    'no-warning-comments': ['off', {terms: ['todo', 'fixme', 'xxx'], location: 'start'}],
    'no-with': 'error',
    'prefer-promise-reject-errors': ['error', {allowEmptyReject: true}],
    'prefer-named-capture-group': 'off',
    'prefer-regex-literals': ['error', {
        disallowRedundantWrapping: true,
    }],
    radix: 'error',
    'require-await': 'error',
    'require-unicode-regexp': 'off',
    'vars-on-top': 'error',
    '@stylistic/wrap-iife': ['error', 'outside', {functionPrototypeMethods: false}],
    yoda: 'error',

    // Errors (from airbnb-base)
    'for-direction': 'error',
    'getter-return': ['error', {allowImplicit: true}],
    'no-async-promise-executor': 'error',
    'no-await-in-loop': 'off',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': ['error', 'always'],
    'no-console': 'warn',
    'no-constant-condition': 'warn',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-dupe-args': 'error',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': 'error',
    'no-empty-character-class': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    '@stylistic/no-extra-parens': ['off', 'all', {
        conditionalAssign: true,
        nestedBinaryExpressions: false,
        returnAssign: false,
        ignoreJSX: 'all',
        enforceForArrowConditionals: false,
    }],
    '@stylistic/no-extra-semi': 'error',
    'no-func-assign': 'error',
    'no-import-assign': 'error',
    'no-inner-declarations': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-obj-calls': 'error',
    'no-promise-executor-return': 'error',
    'no-prototype-builtins': 'error',
    'no-regex-spaces': 'error',
    'no-setter-return': 'error',
    'no-sparse-arrays': 'error',
    'no-template-curly-in-string': 'error',
    'no-unexpected-multiline': 'error',
    'no-unreachable': 'error',
    'no-unreachable-loop': ['error', {
        ignore: [],
    }],
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': ['error', {disallowArithmeticOperators: true}],
    'no-unused-private-class-members': 'off',
    'no-useless-backreference': 'error',
    'no-negated-in-lhs': 'off',
    'require-atomic-updates': 'off',
    'use-isnan': 'error',
    'valid-jsdoc': 'off',
    'valid-typeof': ['error', {requireStringLiterals: true}],

    // Style (from airbnb-base, with customizations)
    '@stylistic/array-bracket-newline': ['error', 'consistent'],
    '@stylistic/array-element-newline': ['error', 'consistent'],
    '@stylistic/array-bracket-spacing': ['error', 'never'],
    '@stylistic/block-spacing': ['error', 'always'],
    '@stylistic/brace-style': ['error', '1tbs', {allowSingleLine: true}],
    camelcase: ['error', {properties: 'never', ignoreDestructuring: false}],
    'capitalized-comments': ['off', 'never', {
        line: {
            ignorePattern: '.*',
            ignoreInlineComments: true,
            ignoreConsecutiveComments: true,
        },
        block: {
            ignorePattern: '.*',
            ignoreInlineComments: true,
            ignoreConsecutiveComments: true,
        },
    }],
    '@stylistic/comma-dangle': ['error', {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        exports: 'always-multiline',
        functions: 'always-multiline',
    }],
    '@stylistic/comma-spacing': ['error', {before: false, after: true}],
    '@stylistic/comma-style': ['error', 'last', {
        exceptions: {
            ArrayExpression: false,
            ArrayPattern: false,
            ArrowFunctionExpression: false,
            CallExpression: false,
            FunctionDeclaration: false,
            FunctionExpression: false,
            ImportDeclaration: false,
            ObjectExpression: false,
            ObjectPattern: false,
            VariableDeclaration: false,
            NewExpression: false,
        },
    }],
    '@stylistic/computed-property-spacing': ['error', 'never'],
    'consistent-this': 'off',
    '@stylistic/eol-last': ['error', 'always'],
    '@stylistic/function-call-argument-newline': ['error', 'consistent'],
    'func-call-spacing': ['error', 'never'],
    'func-name-matching': ['off', 'always', {
        includeCommonJSModuleExports: false,
        considerPropertyDescriptor: true,
    }],
    'func-names': 'warn',
    'func-style': ['off', 'expression'],
    '@stylistic/function-paren-newline': ['error', 'multiline-arguments'],
    'id-denylist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    '@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
    '@stylistic/indent': [
        'error',
        4,
        {
            SwitchCase: 1,
            VariableDeclarator: 1,
            outerIIFEBody: 1,
            FunctionDeclaration: {
                parameters: 1,
                body: 1,
            },
            FunctionExpression: {
                parameters: 1,
                body: 1,
            },
            CallExpression: {
                arguments: 1,
            },
            ArrayExpression: 1,
            ObjectExpression: 1,
            ImportDeclaration: 1,
            flatTernaryExpressions: false,
            ignoredNodes: [
                'JSXElement',
                'JSXElement > *',
                'JSXAttribute',
                'JSXIdentifier',
                'JSXNamespacedName',
                'JSXMemberExpression',
                'JSXSpreadAttribute',
                'JSXExpressionContainer',
                'JSXOpeningElement',
                'JSXClosingElement',
                'JSXFragment',
                'JSXOpeningFragment',
                'JSXClosingFragment',
                'JSXText',
                'JSXEmptyExpression',
                'JSXSpreadChild',
            ],
            ignoreComments: false,
        },
    ],
    'jsx-quotes': ['error', 'prefer-double'],
    '@stylistic/key-spacing': ['error', {beforeColon: false, afterColon: true}],
    '@stylistic/keyword-spacing': ['error', {
        before: true,
        after: true,
        overrides: {
            return: {after: true},
            throw: {after: true},
            case: {after: true},
        },
    }],
    'line-comment-position': ['off', {
        position: 'above',
        ignorePattern: '',
        applyDefaultPatterns: true,
    }],
    '@stylistic/linebreak-style': ['error', 'unix'],
    '@stylistic/lines-between-class-members': ['error', 'always', {exceptAfterSingleLine: false}],
    '@stylistic/lines-around-comment': 'off',
    'lines-around-directive': ['error', {
        before: 'always',
        after: 'always',
    }],
    'max-depth': ['off', 4],
    'max-len': [
        'error',
        {
            code: 120,
            ignoreStrings: false,
            ignoreComments: false,
            ignoreTemplateLiterals: false,
            ignoreTrailingComments: false,
            ignoreUrls: false,
        },
    ],
    'max-lines': ['off', {
        max: 300,
        skipBlankLines: true,
        skipComments: true,
    }],
    'max-lines-per-function': ['off', {
        max: 50,
        skipBlankLines: true,
        skipComments: true,
        IIFEs: true,
    }],
    'max-nested-callbacks': 'off',
    'max-params': ['off', 3],
    'max-statements': ['off', 10],
    'max-statements-per-line': ['off', {max: 1}],
    '@stylistic/multiline-comment-style': ['off', 'starred-block'],
    '@stylistic/multiline-ternary': ['error', 'always-multiline'],
    'new-cap': ['error', {
        newIsCap: true,
        newIsCapExceptions: [],
        capIsNew: false,
        capIsNewExceptions: ['Immutable.Map', 'Immutable.Set', 'Immutable.List'],
    }],
    '@stylistic/new-parens': 'error',
    'newline-after-var': 'off',
    'newline-before-return': 'off',
    '@stylistic/newline-per-chained-call': 'off',
    'no-array-constructor': 'error',
    'no-bitwise': 'off',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-operators': ['error', {
        groups: [
            ['%', '**'],
            ['%', '+'],
            ['%', '-'],
            ['%', '*'],
            ['%', '/'],
            ['/', '*'],
            ['&', '|', '<<', '>>', '>>>'],
            ['==', '!=', '===', '!=='],
            ['&&', '||'],
        ],
        allowSamePrecedence: false,
    }],
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-assign': ['error'],
    '@stylistic/no-multiple-empty-lines': [
        'error',
        {
            max: 1,
            maxEOF: 0,
            maxBOF: 0,
        },
    ],
    'no-negated-condition': 'off',
    'no-nested-ternary': 'error',
    'no-new-object': 'error',
    'no-plusplus': 'off',
    'no-restricted-syntax': [
        'error',
        'ForInStatement',
        'LabeledStatement',
        'WithStatement',
    ],
    'no-spaced-func': 'error',
    'no-tabs': 'error',
    'no-ternary': 'off',
    '@stylistic/no-trailing-spaces': ['error', {
        skipBlankLines: false,
        ignoreComments: false,
    }],
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': ['error', {defaultAssignment: false}],
    '@stylistic/no-whitespace-before-property': 'error',
    '@stylistic/nonblock-statement-body-position': ['error', 'beside', {overrides: {}}],
    '@stylistic/object-curly-spacing': ['error', 'never'],
    '@stylistic/object-curly-newline': [
        'error',
        {
            multiline: true,
            consistent: true,
        },
    ],
    '@stylistic/object-property-newline': ['error', {
        allowAllPropertiesOnSameLine: true,
    }],
    'one-var': ['error', 'never'],
    '@stylistic/one-var-declaration-per-line': ['error', 'always'],
    'operator-assignment': ['error', 'always'],
    '@stylistic/operator-linebreak': ['error', 'before', {overrides: {'=': 'none'}}],
    '@stylistic/padded-blocks': ['error', {
        blocks: 'never',
        classes: 'never',
        switches: 'never',
    }, {
        allowSingleLineBlocks: true,
    }],
    '@stylistic/padding-line-between-statements': [
        'error',
        {
            blankLine: 'always',
            prev: '*',
            next: [
                'try',
            ],
        },
        {
            blankLine: 'always',
            prev: [
                'break',
                'return',
            ],
            next: [
                'case',
                'default',
            ],
        },
        {
            blankLine: 'always',
            prev: [
                'const',
                'let',
                'var',
            ],
            next: '*',
        },
        {
            blankLine: 'any',
            prev: [
                'const',
                'let',
                'var',
            ],
            next: [
                'const',
                'let',
                'var',
            ],
        },
        {
            blankLine: 'always',
            prev: '*',
            next: [
                'break',
                'continue',
                'return',
                'if',
                'function',
                'block',
                'block-like',
            ],
        },
        {
            blankLine: 'any',
            prev: [
                'case',
            ],
            next: [
                'case',
            ],
        },
    ],
    'prefer-exponentiation-operator': 'error',
    'prefer-object-spread': 'error',
    '@stylistic/quote-props': ['error', 'as-needed', {keywords: false, unnecessary: true, numbers: false}],
    '@stylistic/quotes': ['error', 'single', {avoidEscape: true}],
    'require-jsdoc': 'off',
    '@stylistic/semi': ['error', 'always'],
    '@stylistic/semi-spacing': ['error', {before: false, after: true}],
    '@stylistic/semi-style': ['error', 'last'],
    'sort-keys': ['off', 'asc', {caseSensitive: false, natural: true}],
    'sort-vars': 'off',
    '@stylistic/space-before-blocks': 'error',
    '@stylistic/space-before-function-paren': ['error', {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
    }],
    '@stylistic/space-in-parens': ['error', 'never'],
    '@stylistic/space-infix-ops': 'error',
    '@stylistic/space-unary-ops': ['error', {
        words: true,
        nonwords: false,
        overrides: {},
    }],
    '@stylistic/spaced-comment': ['error', 'always', {
        line: {
            exceptions: ['-', '+'],
            markers: ['=', '!', '/'],
        },
        block: {
            exceptions: ['-', '+'],
            markers: ['=', '!', ':', '::'],
            balanced: true,
        },
    }],
    '@stylistic/switch-colon-spacing': ['error', {after: true, before: false}],
    '@stylistic/template-tag-spacing': ['error', 'never'],
    'unicode-bom': ['error', 'never'],
    '@stylistic/wrap-regex': 'off',

    // ES6 (from airbnb-base)
    'arrow-body-style': ['error', 'as-needed', {
        requireReturnForObjectLiteral: false,
    }],
    '@stylistic/arrow-parens': ['error', 'as-needed'],
    '@stylistic/arrow-spacing': ['error', {before: true, after: true}],
    'constructor-super': 'error',
    '@stylistic/generator-star-spacing': ['error', {before: false, after: true}],
    'no-class-assign': 'error',
    '@stylistic/no-confusing-arrow': ['error', {
        allowParens: true,
    }],
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'off',
    'no-new-symbol': 'error',
    'no-restricted-exports': ['error', {
        restrictedNamedExports: [
            'default',
            'then',
        ],
    }],
    'no-restricted-imports': ['off', {
        paths: [],
        patterns: [],
    }],
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': ['error', {
        ignoreDestructuring: false,
        ignoreImport: false,
        ignoreExport: false,
    }],
    'no-var': 'error',
    'object-shorthand': ['error', 'never'],
    'prefer-arrow-callback': ['error', {
        allowNamedFunctions: false,
        allowUnboundThis: true,
    }],
    'prefer-const': ['error', {
        destructuring: 'any',
        ignoreReadBeforeAssign: true,
    }],
    'prefer-destructuring': ['error', {
        VariableDeclarator: {
            array: false,
            object: true,
        },
        AssignmentExpression: {
            array: true,
            object: false,
        },
    }, {
        enforceForRenamedProperties: false,
    }],
    'prefer-numeric-literals': 'error',
    'prefer-reflect': 'off',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-yield': 'error',
    '@stylistic/rest-spread-spacing': ['error', 'never'],
    'sort-imports': ['off', {
        ignoreCase: false,
        ignoreDeclarationSort: false,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: ['none', 'all', 'multiple', 'single'],
    }],
    'symbol-description': 'error',
    '@stylistic/template-curly-spacing': 'error',
    '@stylistic/yield-star-spacing': ['error', 'after'],

    // Variables (from airbnb-base)
    'init-declarations': 'off',
    'no-catch-shadow': 'off',
    'no-delete-var': 'error',
    'no-label-var': 'error',
    'no-restricted-globals': [
        'error',
        {
            name: 'isFinite',
            message: 'Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite',
        },
        {
            name: 'isNaN',
            message: 'Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan',
        },
        'addEventListener',
        'blur',
        'close',
        'closed',
        'confirm',
        'defaultStatus',
        'defaultstatus',
        'event',
        'external',
        'find',
        'focus',
        'frameElement',
        'frames',
        'history',
        'innerHeight',
        'innerWidth',
        'length',
        'location',
        'locationbar',
        'menubar',
        'moveBy',
        'moveTo',
        'name',
        'onblur',
        'onerror',
        'onfocus',
        'onload',
        'onresize',
        'onunload',
        'open',
        'opener',
        'opera',
        'outerHeight',
        'outerWidth',
        'pageXOffset',
        'pageYOffset',
        'parent',
        'print',
        'removeEventListener',
        'resizeBy',
        'resizeTo',
        'screen',
        'screenLeft',
        'screenTop',
        'screenX',
        'screenY',
        'scroll',
        'scrollbars',
        'scrollBy',
        'scrollTo',
        'scrollX',
        'scrollY',
        'self',
        'status',
        'statusbar',
        'stop',
        'toolbar',
        'top',
    ],
    'no-shadow': 'error',
    'no-shadow-restricted-names': 'error',
    'no-undef': 'error',
    'no-undef-init': 'error',
    'no-undefined': 'off',
    'no-unused-vars': [
        'error',
        {
            args: 'after-used',
            ignoreRestSiblings: true,
        },
    ],
    'no-use-before-define': [
        'error',
        {
            functions: false,
        },
    ],

    // Strict (from airbnb-base)
    strict: ['error', 'never'],

    // Node (from airbnb-base)
    'callback-return': 'off',
    'global-require': 'error',
    'handle-callback-err': 'off',
    'no-buffer-constructor': 'error',
    'no-mixed-requires': ['off', false],
    'no-new-require': 'error',
    'no-path-concat': 'error',
    'no-process-env': 'off',
    'no-process-exit': 'off',
    'no-restricted-modules': 'off',
    'no-sync': 'off',

    // Import rules (from airbnb-base)
    'import-x/no-unresolved': 'off',
    'import-x/named': 'error',
    'import-x/default': 'off',
    'import-x/namespace': 'off',
    'import-x/export': 'error',
    'import-x/no-named-as-default': 'error',
    'import-x/no-named-as-default-member': 'error',
    'import-x/no-deprecated': 'off',
    'import-x/no-extraneous-dependencies': 'off',
    'import-x/no-mutable-exports': 'error',
    'import-x/no-commonjs': 'off',
    'import-x/no-amd': 'error',
    'import-x/no-nodejs-modules': 'off',
    'import-x/first': 'error',
    'import-x/imports-first': 'off',
    'import-x/no-duplicates': 'error',
    'import-x/no-namespace': 'off',
    'import-x/extensions': [
        'error',
        'never',
        {
            d: 'always',
            json: 'always',
        },
    ],
    'import-x/order': ['error', {groups: [['builtin', 'external', 'internal']]}],
    'import-x/newline-after-import': 'error',
    'import-x/prefer-default-export': 'off',
    'import-x/no-restricted-paths': 'off',
    'import-x/max-dependencies': ['off', {max: 10}],
    'import-x/no-absolute-path': 'error',
    'import-x/no-dynamic-require': 'error',
    'import-x/no-internal-modules': ['off', {
        allow: [],
    }],
    'import-x/unambiguous': 'off',
    'import-x/no-webpack-loader-syntax': 'error',
    'import-x/no-unassigned-import': 'off',
    'import-x/no-named-default': 'error',
    'import-x/no-anonymous-default-export': ['off', {
        allowArray: false,
        allowArrowFunction: false,
        allowAnonymousClass: false,
        allowAnonymousFunction: false,
        allowLiteral: false,
        allowObject: false,
    }],
    'import-x/exports-last': 'off',
    'import-x/group-exports': 'off',
    'import-x/no-default-export': 'error',
    'import-x/no-named-export': 'off',
    'import-x/no-self-import': 'error',
    'import-x/no-cycle': ['error', {maxDepth: Infinity}],
    'import-x/no-useless-path-segments': ['error', {commonjs: true}],
    'import-x/dynamic-import-chunkname': ['off', {
        importFunctions: [],
        webpackChunknameFormat: '[0-9a-zA-Z-_/.]+',
    }],
    'import-x/no-relative-parent-imports': 'off',
    'import-x/no-unused-modules': ['off', {
        ignoreExports: [],
        missingExports: true,
        unusedExports: true,
    }],
    'import-x/no-import-module-exports': ['error', {
        exceptions: [],
    }],
    'import-x/no-relative-packages': 'error',

    // Custom plugin rules
    'import-newlines/enforce': [
        'error',
        {
            items: 6,
            'max-len': 120,
        },
    ],
    'newline-destructuring/newline': [
        'error',
        {
            maxLength: 100,
            itemsWithRest: Infinity,
            items: Infinity,
        },
    ],

    // Jest rules
    'jest/consistent-test-it': [
        'error',
        {
            fn: 'it',
        },
    ],
    'jest/no-large-snapshots': 'off',
    'jest/prefer-expect-resolves': 'error',
    'jest/prefer-lowercase-title': [
        'error',
        {
            ignore: ['describe'],
        },
    ],
    'jest/prefer-spy-on': 'error',
    'jest/require-top-level-describe': 'error',
    'jest/prefer-to-contain': 'error',
    'jest/prefer-hooks-on-top': 'error',
    'jest/prefer-equality-matcher': 'error',
    'jest/no-test-return-statement': 'error',
};

export {baseRules};

// Factory function to create JavaScript config with the plugin reference
export function createJavaScriptConfig(plugin: ESLint.Plugin): Linter.Config[] {
    return [
        jest.configs['flat/recommended'],
        {
            name: '@croct/javascript',
            plugins: {
                '@stylistic': stylistic,
                '@eslint-community/eslint-comments': eslintComments,
                'import-newlines': importNewlines,
                // import-x exports types using ESLint v8 for compatibility reasons,
                // but it is compatible with ESLint v9 as well.
                'import-x': importX as unknown as ESLint.Plugin,
                'newline-destructuring': newlineDestructuring,
                '@croct': plugin,
            },
            languageOptions: {
                ecmaVersion: 2018,
                sourceType: 'module',
                globals: {
                    ...globals.es2017,
                    ...globals.node,
                },
            },
            rules: {
                ...eslintComments.configs.recommended.rules,
                ...baseRules,
            },
        },
        {
            name: '@croct/javascript/tests',
            files: [
                'src/**/*.test.js',
                'test/**/*.js',
            ],
            rules: {
                'no-new-object': 'off',
            },
        },
    ];
}
