name: Deploy release

on:
  release:
    types:
      - published

jobs:
  deploy:
    uses: croct-tech/shared-public-configs/.github/workflows/publish-public-npm-package.yml@master
    with:
      build-dir: "dist"
      prepare-script: >-
        cp package.json LICENSE README.md dist/ &&
        cd dist &&
        jq --arg version "${GITHUB_REF##*/}" '.version = $version | .main |= sub("^dist/"; "") | .types |= sub("^dist/"; "")' package.json > package.tmp.json &&
        mv package.tmp.json package.json
